# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd9af2ba50112b717e2d3801a76ff72f9ea083b99d3e542db83dce1edbd3704e6ef799880897215182e1a038bd2f65352aee6e15c89315a2dfc958f5fb77dd09

test:
  secret_key_base: a7e3616d55e9a2e9e4677e06f4bef52851076713f93a3b370d640f4a19a2b995b4ee412ddc301e1d3761420b77db5c0168960c193dfe5c21692d4836df72ad01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
